### ISSUE TITLE
I don`t see sample.env can anyone help me pls

### ISSUE THREAD

**Issue by MrDiscordAnimation** [pieromqwerty/Replit.sh#3]
I don`t see sample.env can anyone help me pls because in the instruction it says rename sample.env to .env or maybe i have to create one

**Comment by MntRushmore** [comment]
Same Bro @MrDiscordAnimation @timmyichen @Mosrod @pieromqwerty @hyperupcall

**Comment by piemadd** [comment]
Closed due to repository being archived. Please check out Replit.sh v4 [here](https://github.com/replit-discord/Replit.sh-v4).
